### ISSUE TITLE
Add object support

### ISSUE THREAD

**Issue by vinnydiehl** [wildfiler/drtiled#14]
I am working on adding support for objects:
![2023-04-27-044314_1003x573_scrot](https://user-images.githubusercontent.com/1045694/234859691-9141917b-075c-457a-b73f-4a0b2e8c4de2.png)

I have the XML loaded and have a basic API set up:
```
#<Tiled::ObjectLayer attributes=#<Tiled::Attributes color="#ff0000", r=255, g=0, b=0, id="3", name="object", visible=true>, objects=[
  #<Tiled::TiledObject attributes=#<Tiled::Attributes height=448.0, id="1", points=nil, shape=:rectangle, width=64.0, x=1024.0, y=64.0>>,
  #<Tiled::TiledObject attributes=#<Tiled::Attributes height=256.0, id="3", points=nil, shape=:rectangle, width=64.0, x=832.0, y=416.0>>,
  #<Tiled::TiledObject attributes=#<Tiled::Attributes height=64.0, id="4", points=nil, shape=:rectangle, width=1280.0, x=0.0, y=0.0>>,
  #<Tiled::TiledObject attributes=#<Tiled::Attributes height=384.0, id="5", points=nil, shape=:rectangle, width=64.0, x=0.0, y=64.0>>,
  #<Tiled::TiledObject attributes=#<Tiled::Attributes height=32.0, id="6", points=nil, shape=:rectangle, width=128.0, x=640.0, y=128.0>>,
  #<Tiled::TiledObject attributes=#<Tiled::Attributes height=32.0, id="7", points=nil, shape=:rectangle, width=128.0, x=448.0, y=224.0>>,
  #<Tiled::TiledObject attributes=#<Tiled::Attributes height=32.0, id="8", points=nil, shape=:rectangle, width=128.0, x=160.0, y=128.0>>,
  #<Tiled::TiledObject attributes=#<Tiled::Attributes height=196.109, id="16", points=nil, shape=:ellipse, width=186.233, x=304.745, y=434.782>>,
  #<Tiled::TiledObject attributes=#<Tiled::Attributes height=0.0, id="17", points=[{:x=>0, :y=>0}, {:x=>64, :y=>64}, {:x=>64, :y=>0}], shape=:polygon, width=0.0, x=583.566, y=506.55>>
]>
```

And I have rectangles rendering by way of an `ObjectLayer#primitives` method which can be fed into `args.outputs.debug`:
![2023-04-27-070250_1924x1066_scrot](https://user-images.githubusercontent.com/1045694/234860342-c5b4809b-5b2f-440d-8289-270489ff1de7.png)

If you like the direction I'm taking this, you can expect a PR soon. I eventually plan on implementing collision algorithms directly into this library for my own purposes; if you like the sound of that as well, we can discuss, possibly in a separate thread after this is merged.

**Comment by wildfiler** [comment]
I would love to see PR, looks awesome :)
Right now I'm not sure about collision detection build in library, in future I'm planing to separate rendering part from map part to make library lighter and easier to integrate with other libraries, but for now I think it can benefit from integrated tools like rendering and collision detection. At least it will show how to better organize things.

One note, I see you use hash for points in the polygon, maybe make sense to use array? in DR you can address first two elements of array as `x` and `y`. Not sure if it affects memory footprint, but I think arrays should be lighter.

But in any case, I'll be glad to see the PR :)

**Comment by vinnydiehl** [comment]
>in DR you can address first two elements of array as x and y

Thanks, I didn't think of this!

An issue that I've run into with rendering the objects is that the most efficient way to draw an ellipse is to construct a render target, but (correct me if I'm wrong) you can't do this without `args`. My approach has been to replace `ObjectLayer#primitives` with a `ObjectLayer#render_debug` method that unfortunately needs `args` passed in:

```ruby
    def render_debug(args)
      return unless visible?

      # Resolution of circle
      radius = 300
      diameter = 2 * radius

      unless args.state.tiled_circle_initialized
        # Draw a circle by iterating over the diameter and drawing a bunch
        # of lines that get wider as they reach the center
        diameter.times do |i|
          height = i - radius
          length = Math::sqrt(radius * radius - height * height)
          args.render_target(:ellipse).lines << {
            x: i, y: radius - length, x2: i, y2: radius + length,
            r: r, g: g, b: b
          }
        end

        args.state.tiled_circle_initialized = true
      end

      @objects.each do |object|
        case object.shape
        when :rectangle
          data = {
            x: object.x, y: object.y,
            w: object.width, h: object.height,
            r: r, g: g, b: b
          }

          args.outputs.debug << [
            data.merge({ primitive_marker: :solid, a: 100 }),
            data.to_border
          ]
        when :ellipse
          args.outputs.debug << {
            x: object.x, y: object.y,
            w: object.width, h: object.height,
            path: :ellipse,
            source_x: 0, source_y: 0,
            source_w: diameter, source_h: diameter,
            a: 100
          }
        end
      end
    end

```

The alternative is to return a shit ton of line primitives from `ObjectLayer#primitives`, and the algorithm to determine the relative positioning of the lines would need to run every frame. This is only for debugging and I'm sure that it wouldn't come close to hitting your framerate, but it seems needlessly inefficient. What are your thoughts?

**Comment by wildfiler** [comment]
Hmm, maybe use a png sprite with the white circle? Then you can return primitives as before. It can lead to blurry borders because of scaling, but for debugging purposes it is ok.

Non trivial thing as I see :)

**Comment by wildfiler** [comment]
Maybe do the rendering as a second step? Because rendering objects in-game is only for debugging, but if they are loaded you can use them in-game even if you cannot see them :D 

WDYT?

**Comment by vinnydiehl** [comment]
Yeah, the objects are loaded along with the rest of the map and contain all of the information necessary to do collision calculations and such. This method is simply intended to be called from the game's rendering code if the user so desires, something like:

```ruby
$map.objectlayers["object"].render_debug(@args)
```

And it of course honors the layer visibility set in Tiled.

A PNG sprite would work but kinda hacky IMO, also wouldn't honor the color set in Tiled.

In other news, I got polygons rendering, that was fun:
![2023-04-28-134114_1889x1062_scrot](https://user-images.githubusercontent.com/1045694/235218622-7a23539a-c54d-4255-9cdf-878a64f24d3b.png)

**Comment by wildfiler** [comment]
> This method is simply intended to be called from the game's rendering code if the user so desires

Looks good to me 👍 

> A PNG sprite would work but kinda hacky IMO, also wouldn't honor the color set in Tiled.

All gamedev is kinda one big hack for me :D

About the color of the sprite, you can set sprite's color with 'r', 'g', 'b', 'a' attributes(or keys in case of hash), and DR will tint the sprite by this color, so the white circle png can be any color you like :)

Impressive work, indeed polygons look like a lot of fun )
