### ISSUE TITLE
`s/TiledObject/MapObject`

### ISSUE THREAD

**Issue by vinnydiehl** [wildfiler/drtiled#33]
I wasn't quite sure what to name this at first, since obviously `Object` was out of the question. I've come to find out that they're called `MapObject` internally within Tiled; I think it has a better ring to it/looks more professional without the "Tiled" repetition.

The feature has already been released, but we could always alias it for backwards compatibility if that's important at this stage.

It's not really a big deal, figured I'd make an issue to make sure you're not opposed before sending a patch.

**Comment by wildfiler** [comment]
Until 1.0.0 backward compatibility isn't a concern, I think.

I like `MapObject`, `TiledObject` bothered me as well :)
